# Generated by Django 2.2.5 on 2020-03-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='api_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
