# Generated by Django 2.2.5 on 2020-03-07 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dovavision', '0002_company'),
        ('stock', '0003_auto_20200307_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='index_id',
            new_name='index',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='company_id',
        ),
        migrations.AddField(
            model_name='stock',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dovavision.Company'),
        ),
    ]
